# Запросить документ по id как BankUser, BankUser имеет доступ к счетам с gl2 30101
GET http://localhost:5136/account/1?userId=BankUser
Accept: application/json

###

# Запросить документ по id как BankUser, BankUser не имеет доступа к счетам с gl2 30102
GET http://localhost:5136/account/4?userId=BankUser
Accept: application/json

###

POST http://localhost:5136/document?userId=Supervisor
Content-Type: application/json

{
  "Id": 5,
  "DocumentTypeId": "Account",
  "BranchId": 1,
  "OfficeId": 3
}

###
PUT http://localhost:5136/document?userId=Supervisor
Content-Type: application/json

{
  "DocumentTypeId": "Account",
  "BranchId": 1,
  "OfficeId": 3
}

###
# запросить все документы как суперпользотваль
GET http://localhost:5136/document?userId=Superuser
Accept: application/json

###

# запросить все документы как банковский пользотваль
GET http://localhost:5136/document?userId=BankUser
Accept: application/json

###

# запросить все документы как банковский пользотваль
GET http://localhost:5136/document?userId=BankUser
Accept: application/json

###

# запросить все документы как банковский пользователь у которого есть права в branchId=1 (см. класс OrgStructure)
GET http://localhost:5136/document?userId=BranchUser&branchId=1
Accept: application/json

###

# запросить все документы как банковский пользователь у которого есть права в branchId=1 из другого branchId=2 (см. класс OrgStructure)
GET http://localhost:5136/document?userId=BranchUser&branchId=2
Accept: application/json

###

# запросить все документы как банковский пользователь у которого есть права в branchId=1 и officeId=3, regionalOfficeId может быть опущен (см. класс OrgStructure)
GET http://localhost:5136/document?userId=BranchUser&branchId=1&officeId=3
Accept: application/json

###